#!/bin/bash
#cat logo.txt

echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdhysoo++///:::////++oosyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhs+/-.      *.-:.*///////. ::-.*     *.-/+shmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyo:.    *-/+s+ mNMMMMMs.MMMMMMMo.MMMMMMN/.ys+:-*    ./oymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmy+-    *:: hNMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMN:.+-*   *:oyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms/*   *:ohmMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMmy+-    ./ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy/.   *:/ NMMMMMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMMMMM:-o-    .+hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms:    .+hMMh NMMMMMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMMMMM::MMNh+.   *:yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMms-     omMMMMMh NMMMMMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMMMMM::MMMMMMd-     :sNMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMNy:    .oy mMMMMMMh NMMMMMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMMMMM::MMMMMMM/:d+*    :hMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMd+*   */dMMh mMMMMMMh NMMMMMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMMMMM::MMMMMMM/:MMMh/    *+mMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMy-    .sNMMMMh mMMMMMMh NMMMMMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMMMMM::MMMMMMM/:MMMMMNo*    :hMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMNs*    - mMMMMMMh mMMMMMMh NMMMMMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMMMMM::MMMMMMM/:MMMMMMM:.-    .sMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMNo*    /dm mMMMMMMh mMMMMMMh NMMMMMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMMMMM::MMMMMMM//MMMMMMM:/Mh:    *sNMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMNo*    /mMMm mMMMMMMh mMMMMMMh NMMMMMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMMMMM::MMMMMMM/+MMMMMMM:+MMMd:    *sNMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMNo*    :dMMMMm mMMMMMMh mMMMMMMh NMMMMMMy NMMMMMMy MMMMMMMs.MMMMMMMo.MMMMMMM/-MMMMMMM/-MMMMMMM::MMMMMMM:+MMMMMMM:+MMMMMh-    *sMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33m/----------*     *------- -------. -------. -------. -------. -------. -------* -------**-------**-------**-------**-------**-------      .-----------\033[0m"
echo -e "\033[1;33ms+++++++:                                                                                                                                    /+++++++o\033[0m"
echo -e "\033[1;33mMMMMMMN+                                                                                                                                     *sMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMd.                                                  ***                     **                                                            -mMMMMM\033[0m"
echo -e "\033[1;33mMMMM+       -------.------. .------. -------*------.   .-----* *---   ---*    *.----.    *--. .---------------.-.  .--  .-. *--. *--   .-.       sMMMM\033[0m"
echo -e "\033[1;33mMMm-        --*****.-....--..-.***** --******--...--. .--***--.*---* *---*    --.**.--   .--- ***--.**.--******--  ---  .-* .---  .-. *--*        :NMM\033[0m"
echo -e "\033[1;33mMh*         --     .-.   .-..-.      -:      --    --*--*   *--*-.-. .---*   .-.    ..   --.-.   .-.  *--      --**---* --  ----. *--*.-.          .dM\033[0m"
echo -e "\033[1;33ms           --....*.-.***--*.--..... --..... --    .----     --*-.-. .---*   --*  ****  .-.*--   .-.  *--..... .-.*-.-.*-. .-.*--  .----            *y\033[0m"
echo -e "\033[1;33my           ------..------- .--..... --..... --    .----     --*-..-*-.--*   --.  ----* --* --*  .-.  *--..... *--.- --.-* --* --*  .--*             s\033[0m"
echo -e "\033[1;33mMh*         --     .-.  *--*.-.      -:      --    --.--*   *--*-.*-.-*--*   .-.    --**------.  .-.  *--       ---- .--- *------.  *--            *hM\033[0m"
echo -e "\033[1;33mMMm-        --     .-.   .-*.-.***** --***** --***.-. .-.* *--.*-. --- --*   *--.  .--*.-....--* .-.  *--****** .--. *--. .-....--* *--           .mMM\033[0m"
echo -e "\033[1;33mMMMM/       --     .-.   .-..-------*-------*------.   .-----. *-. .-. --*    *-----.-.--*   .-. .-.  *-------. *--* *--**--    .-. *--          /NMMM\033[0m"
echo -e "\033[1;33mMMMMMy*     **     ***    ** ******* ******* *****      **.**   *   *  **       ***  ****     ** ***   ********  **   **  **     **  **        *yMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMN:                                                                                                                                      :mMMMMMM\033[0m"
echo -e "\033[1;33mhhhhhhhh/                                                                                                                                    :hhhhhhhd\033[0m"
echo -e "\033[1;33m                                                                                                                                                     :\033[0m"
echo -e "\033[1;33mNNNNNNNNNNNd-    *oNNNNNN/:NNNNNNN::NNNNNNN:/NNNNNNN-/NNNNNNN-+NNNNNNN.oNNNNNNN oNNNNNNm yNNNNNNm yNNNNNNm hNNNNNNd dNNNNNNd mNNNNNs*    -hNNNNNNNNNNN\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMy.    .yMMMM+:MMMMMMM::MMMMMMM:/MMMMMMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMMMMMMN hMMMMMMm mMMMMMMm NMMMh-    .yMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMs*    -hMM+/MMMMMMM:/MMMMMMM:/MMMMMMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMMMMMMN hMMMMMMm mMMMMMMm NMd:    *sNMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMNs.    -h//MMMMMMM:/MMMMMMM:/MMMMMMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMMMMMMN hMMMMMMm mMMMMMMm h:    *sNMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMy.     :MMMMMMM-/MMMMMMM:/MMMMMMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMMMMMMN hMMMMMMm mMMMMMMy     .sNMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMh:    .oNMMMM-/MMMMMMM:/MMMMMMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMMMMMMN hMMMMMMm mMMMNs.    -yMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMm+*    /hMM-/MMMMMMM:/MMMMMMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMMMMMMN hMMMMMMm mMd/*   *+dMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMy:    .o.oMMMMMMM:/MMMMMMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMMMMMMN hMMMMMMm +.    :yNMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs-    .omMMMMM:/MMMMMMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMMMMMMN hMMMMms-    -omMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms-    .+hMM:/MMMMMMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMMMMMMN hMdo.    -omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy/*   *:./MMMMMMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMMMMMMd -*   *:yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds:*   *:ohNMM-/MMMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMMMN yMNho:*   *:odMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds/.    *:*:dNMMMMM-oMMMMMMM.sMMMMMMM sMMMMMMN yMMMMNdy -.    ./sdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNds+-*    *-/os./mNMMMMM.sMMMMMMM sMMMMNmh /o/-*    *-/sdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyo/:.*      *.-- .::::::: .-.*       .:/oydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"
echo -e "\033[1;33mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdhyso+++///::::///+++osyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\033[0m"

echo ""
echo -e "\033[1;33mWelcome to the Freedom Gateway Linux Installer!\033[0m"
echo -e "\033[1;33mThis is the first of two scripts, and it will handle the tedium of getting the basic system installed automatically.\033[0m"
